on:
  push:
    branches: [main]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Add node_modules
        run: yarn install
      - name: Build
        run: yarn build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          port: 21
          server: methyx.fr
          username: git@methyx.fr
          password: ${{ secrets.git_ftp_password }}
          local-dir: ./dist/
          server-dir: ./
