name: Deploy Front on RPI

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Compile
        run: yarn install
      - name: Build
        run: yarn build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: phil
          server: methyx.ddns.net
          port: 22 # default is 22
          ssh_private_key: ${{ secrets.SSH_RPI_FRONT }}

          # will put all file under this path
          local_path: ./dist/* # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www/html

          # sftp args
          args: "-o ConnectTimeout=5"
